### ISSUE TITLE
Add-on cannot be installed

### ISSUE THREAD

**Issue by misosec** [odinuge/hassio-addons#1]
After adding repository and clicking 'Install', nothing happens.

hass.io 0.58.1 on RasPi 3

**Comment by odinuge** [comment]
Hi, 
Will continue the [conversation](https://github.com/odinuge/hassio-addons/commit/c2fe8f7691ddd406f8d954de7499e25e03d55d7f#commitcomment-25874729) in this issue..

It is currently not possible to use password (atleast my version...). The addon creates an SSH-key on first startup, that is uses to connect. This results in much better security.

The public key of the ssh-key (the one you need on the server you are connecting to) is printed during startup in the log, and looks like this:
![screenshot from 2017-11-27 18-34-01](https://user-images.githubusercontent.com/1467188/33280325-f7687990-d3a1-11e7-82d3-bcd79fd60e25.png).

Copy the whole line containing `ssh-rsa` into the `~/.ssh/authorized_keys` on your server.

**Comment by misosec** [comment]
Hello,
so the key starts with `ssh-rsa` and ends with `autossh`, right? I had to create `authorized_keys` file on my VPS because there wasn't a such a file. Its not working for me so far. 
In AutoSSH Log are lines
 ```
Your identification has been saved in /data/ssh_keys/autossh_rsa_key.
Your public key has been saved in /data/ssh_keys/autossh_rsa_key.pub.
```

but I cannot find that files anywhere. Maybe thats the reason why its not working?

btw, tunneling is working when I enter `ssh root@xxx.xxx.xxx.xxx -R 8123:192.168.100.220:8123` directly into hass.io command line.

Thank you.

**Comment by misosec** [comment]
... and when I click Start it seems ok and I can see Stop, Restart, but when I reload page, there is only Start again like it wasnt started at all.
Any suggestion?
Thank you.

**Comment by odinuge** [comment]
Looks like you found the right key. It may be a problem with the unix-permissions of the `.ssh` folder and the `.ssh/authorized_keys` file. The file (and folder) should only be readable from the account it belongs to. You can try [this answer](https://stackoverflow.com/questions/6377009/adding-public-key-to-ssh-authorized-keys-does-not-log-me-in-automatically), and check if it works (on the VPS).

The reason you can't find the key, is becuase the ssh-addon in hass.io runs in a separate docker-container that cannot reach the files from other containers (ie. the autossh-addon).

**Comment by odinuge** [comment]
You must also ensure that the `.ssh` (containing `authorized_keys` file) folder is located in the home directory of the user you are going to use. Since you use the root-user, it should be `/root/.ssh/authorized_keys`..

**Comment by misosec** [comment]
It just wont stay running. Everytime I refresh hass.io webpage, the `State` is back to `stopped`.
What can be wrong?
Thanks.

**Comment by odinuge** [comment]
Hi,

I have now updated this repo, so this addon shold work now. :smile: 

If you add `-v` to the ssh-options, it will print the status for you, so you can see what is happening. If you then get `debug1: All remote forwarding requests processed`, everything should be ok. You can also check the logs of the ssh server, to see what is happening.

Add this line to your config:
```json
{
  "other_ssh_options": "-v"
}
```

**Comment by misosec** [comment]
Seems like its working now! Nice! Thank You! :-)
