### ISSUE TITLE
Bad gateway on Home Assistant (rpi) restart

### ISSUE THREAD

**Issue by matthieup240** [odinuge/hassio-addons#10]
Hi,

When I disconnect the rpi to the internet cable and reconnect it after some hours, the connection is working.
When I restart the Home Assistant, it is working too.

But, when I power off the rpi, I have a bad gateway.
Here is my configuration :

`hostname: home-assistant.example.com
ssh_port: '22'
username: user
remote_forwarding:
  - '172.17.0.1:44400:172.17.0.1:8123'
local_forwarding:
  - ''
other_ssh_options: '-o "ExitOnForwardFailure yes"'
monitor_port: '0'
gatetime: '30'
`

Is there something I forget ?

Thanks

**Comment by jcgoette** [comment]
Check the logs. It might be returning something like `command-line: line 0: Bad configuration option: exitonforwardfailure=yes`.

If so, you want `other_ssh_options: '-o ExitOnForwardFailure=yes'`.
