### ISSUE TITLE
Addons not available on Ubuntu/docker

### ISSUE THREAD

**Issue by nenonano** [odinuge/hassio-addons#4]
Hi there

I 'm trying to use autossh on my hassio on ubuntu/docker install.. I restored my backup (previously running on raspy) and I can see your repository among the ones I had, but no addons from you are available.

AFAICS, the issue is because your addons are missing the 
"arch": ["armv7", "armhf", "amd64", "aarch64", "i386"],
key in config.json

I'm suffering the same issues with other addons as well, coming from other repos

**Comment by pjcarly** [comment]
Hey @odinuge ,

You have added 5 supported platforms, of which you have 4 docker images on your docker-hub
- armhf
- amd64
- aarch64
- i386

But the following image is missing from docker-hub:
- armv7

Causing the issue:
`[hassio.docker.interface] Can't install odinuge/hassio-addon-autossh-armv7:0.2.3 -> 404 Client Error: Not Found ("pull access denied for odinuge/hassio-addon-autossh-armv7, repository does not exist or may require 'docker login'")`

If i force the use of platform `armhf`, I get the following error:
`[hassio.docker.interface] Can't install odinuge/hassio-addon-autossh-armhf:0.0.2 -> 404 Client Error: Not Found ("manifest for odinuge/hassio-addon-autossh-armhf:0.0.2 not found").`

**Comment by odinuge** [comment]
Hi @pjcarly! Thanks for noticing! Did a version bump and uploaded the new version for all arches <https://hub.docker.com/?namespace=odinuge>.

Can you check if it works?

**Comment by pjcarly** [comment]
Awesome. It is working perfectly. Cheers!
If you're interested i'm using your addon, slightly modified, to expose home assistant to the internet over an ssh tunnel, instead of duckdns/port forwarding nonsense.

https://carly.be/expose-home-assistant-through-ssh-tunnel/

**Comment by odinuge** [comment]
Ahh, nice!

Cool article, and thanks for the mention 😀
