### ISSUE TITLE
Support for environment variables

### ISSUE THREAD

**Issue by dircr** [odinuge/hassio-addons#6]
Autossh sometimes fails to start when internet is not ready, e.g. Hass.io and router start at the same time after power failure and router takes more time to connect to internet. Autossh can handle this with env variables (AUTOSSH_GATETIME) but there's no way to define them in the add-on.

**Comment by gandhimaulik** [comment]
Same is happening with me..

More over, 
If previous connection was disconnected just few seconds ago, remote server will refuse another connection to same port. In that case autossh is not attempting another try after a minute or ever. 

So Home assistant is not available for remote access until next restart.

**Comment by dircr** [comment]
My workaround for this is to setup node-red (or other automation) to check periodically if hassio is reachable from the internet and restart autossh add-on otherwise.

**Comment by gandhimaulik** [comment]
That is Awesome.. 😎
I did not thought of it. May be i am not used to home assistant yet..

**Comment by odinuge** [comment]
This should be fixed by https://github.com/odinuge/hassio-addons/pull/8. Feel free to reopen if that is not the case.

**Comment by thiagoprati** [comment]
> My workaround for this is to setup node-red (or other automation) to check periodically if hassio is reachable from the internet and restart autossh add-on otherwise.

CAN you share how to make this Automation?
