### ISSUE TITLE
Addition to offical addons

### ISSUE THREAD

**Issue by ThomDietrich** [odinuge/hassio-addons#9]
Hey there!
I just tested your addon and it worked right out of the box. Used it to forward my local HA server to a publicly reachable server, there a reverse proxy (caddy) takes care of serving the webpage from 127.0.0.1 with Let's Encrypt certificate. The whole thing took me 15min to set up. Amazing. Thanks!

I've created this ticket to ask if there is a specific reason why you decided to not (or not yet) add this project to the official addons repository. I would be happy to help where I can.

**Comment by odinuge** [comment]
Hi @ThomDietrich!

So good to hear that you are pleased with the addon! I do however have to specific reason other than the fact that this addon was originally created in 2017 right after the release off hassio, and back then I just didn't think about adding it to the official addon repository.

> I would be happy to help where I can.

Feel free to add this (both the addons for that matter) into the official repository if the owners of the official addon repo allow it. This repo is licensed under MIT, but I'll allow you to copy/use it as you want, including adding it to the official addon repository without having to think about the license. Ill be more than happy if you quote my github tag @odinuge and/or link to this repo, but thats all up to you. :smile:

**Comment by odinuge** [comment]
Ill close the issue, but feel free to comment if there are some new news!
